var searchIndex = JSON.parse('{\
"__TOC":{"doc":"Table of contents📁 crates📁 graph dijkstra📁 …","i":[],"p":[]},\
"dijkstra":{"doc":"Performs Dijkstra’s algorithm.","i":[[5,"costs","dijkstra","Computes costs for each node.",null,[[]]]],"p":[]},\
"fastout":{"doc":"","i":[[23,"fastout","fastout","",null,null]],"p":[]},\
"gcd":{"doc":"Calculates a Greatest Common Divisor (GCD).","i":[[5,"gcd","gcd","Calculates a Greatest Common Divisor (GCD).",null,[[["u64",15]],["u64",15]]]],"p":[]},\
"input":{"doc":"Provides <code>input!</code> macro.","i":[[5,"usize1","input","",null,[[["usize",15]],["usize",15]]],[5,"bytes","","",null,[[["string",3]],[["u8",15],["vec",3]]]],[8,"Readable","","A trait representing which type can be read.",null,null],[16,"Output","","",0,null],[10,"read","","",0,[[["fnmut",8]]]],[4,"Usize1","","1-based index.",null,null],[4,"Bytes","","Reads a string as <code>Vec<u8></code>.",null,null],[14,"input","","A <code>input!</code> macro.",null,null],[11,"from","","",1,[[]]],[11,"into","","",1,[[]]],[11,"borrow","","",1,[[]]],[11,"borrow_mut","","",1,[[]]],[11,"try_from","","",1,[[],["result",4]]],[11,"try_into","","",1,[[],["result",4]]],[11,"type_id","","",1,[[],["typeid",3]]],[11,"from","","",2,[[]]],[11,"into","","",2,[[]]],[11,"borrow","","",2,[[]]],[11,"borrow_mut","","",2,[[]]],[11,"try_from","","",2,[[],["result",4]]],[11,"try_into","","",2,[[],["result",4]]],[11,"type_id","","",2,[[],["typeid",3]]],[11,"read","","",1,[[["fnmut",8]],["usize",15]]],[11,"read","","",2,[[["fnmut",8]],[["u8",15],["vec",3]]]]],"p":[[8,"Readable"],[4,"Usize1"],[4,"Bytes"]]},\
"miller_rabin":{"doc":"Performs Miller-Rabin test.","i":[[5,"is_prime","miller_rabin","Performs Miller-Rabin test.",null,[[["u64",15]],["bool",15]]]],"p":[]},\
"montmort_number":{"doc":"Computes Montmort numbers.","i":[[5,"montmort","montmort_number","Computes Montmort numbers.",null,[[["usize",15]],[["usize",15],["vec",3],["from",8],["add",8],["sub",8],["copy",8],["mul",8]]]]],"p":[]},\
"partition_point":{"doc":"Computes the index of the partition point.","i":[[8,"RangeBoundsExt","partition_point","",null,null],[11,"partition_point","","",0,[[]]],[8,"SliceExt","","",null,null],[16,"Item","","",1,null],[10,"partition_point","","",1,[[],["usize",15]]],[8,"PrimitiveInteger","","",null,null],[18,"ZERO","","",2,null],[18,"ONE","","",2,null],[18,"MIN_VALUE","","",2,null],[18,"MAX_VALUE","","",2,null]],"p":[[8,"RangeBoundsExt"],[8,"SliceExt"],[8,"PrimitiveInteger"]]},\
"rho":{"doc":"Performs Pollard’s rho algorithm.","i":[[5,"factorize","rho","Performs Pollard’s rho algorithm.",null,[[["u64",15]],[["vec",3],["u64",15]]]]],"p":[]},\
"sieve":{"doc":"A prime sieve.","i":[[3,"Sieve","sieve","A prime sieve.",null,null],[11,"new","","",0,[[["usize",15]]]],[11,"is_prime","","",0,[[["usize",15]],["bool",15]]],[11,"primes","","",0,[[]]],[11,"factorize","","",0,[[["usize",15]],["vec",3]]],[11,"from","","",0,[[]]],[11,"into","","",0,[[]]],[11,"borrow","","",0,[[]]],[11,"borrow_mut","","",0,[[]]],[11,"try_from","","",0,[[],["result",4]]],[11,"try_into","","",0,[[],["result",4]]],[11,"type_id","","",0,[[],["typeid",3]]]],"p":[[3,"Sieve"]]},\
"tonelli_shanks":{"doc":"Performs Tonelli–Shanks algorithm.","i":[[8,"ModIntBaseExt","tonelli_shanks","Performs Tonelli–Shanks algorithm.",null,null],[11,"sqrt","","Performs Tonelli–Shanks algorithm.",0,[[],["option",4]]]],"p":[[8,"ModIntBaseExt"]]},\
"xorshift":{"doc":"Xorshift.","i":[[3,"Xorshift64","xorshift","64-bit Xorshift.",null,null],[11,"new","","",0,[[]]],[11,"next_u64","","",0,[[],["u64",15]]],[11,"from","","",0,[[]]],[11,"into","","",0,[[]]],[11,"into_iter","","",0,[[]]],[11,"to_owned","","",0,[[]]],[11,"clone_into","","",0,[[]]],[11,"borrow","","",0,[[]]],[11,"borrow_mut","","",0,[[]]],[11,"try_from","","",0,[[],["result",4]]],[11,"try_into","","",0,[[],["result",4]]],[11,"type_id","","",0,[[],["typeid",3]]],[11,"next","","",0,[[],[["option",4],["u64",15]]]],[11,"clone","","",0,[[],["xorshift64",3]]],[11,"default","","",0,[[]]],[11,"fmt","","",0,[[["formatter",3]],["result",6]]]],"p":[[3,"Xorshift64"]]}\
}');
initSearch(searchIndex);